// +build !

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/barpilot/node-labeler-operator/pkg/apis/barpilot/v1alpha1.Labeler":     schema_pkg_apis_barpilot_v1alpha1_Labeler(ref),
		"github.com/barpilot/node-labeler-operator/pkg/apis/barpilot/v1alpha1.LabelerSpec": schema_pkg_apis_barpilot_v1alpha1_LabelerSpec(ref),
	}
}

func schema_pkg_apis_barpilot_v1alpha1_Labeler(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "Labeler is the Schema for the labelers API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/barpilot/node-labeler-operator/pkg/apis/barpilot/v1alpha1.LabelerSpec"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/barpilot/node-labeler-operator/pkg/apis/barpilot/v1alpha1.LabelerSpec", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_barpilot_v1alpha1_LabelerSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "LabelerSpec defines the desired state of Labeler",
				Properties: map[string]spec.Schema{
					"nodeSelectorTerms": {
						SchemaProps: spec.SchemaProps{
							Description: "Required. A list of node selector terms. The terms are ORed.",
							Type:        []string{"array"},
							Items: &spec.SchemaOrArray{
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Ref: ref("k8s.io/api/core/v1.NodeSelectorTerm"),
									},
								},
							},
						},
					},
					"merge": {
						SchemaProps: spec.SchemaProps{
							Description: "MergeSpec sets everything that will be added to selected nodes",
							Ref:         ref("github.com/barpilot/node-labeler-operator/pkg/apis/barpilot/v1alpha1.MergeSpec"),
						},
					},
				},
				Required: []string{"nodeSelectorTerms"},
			},
		},
		Dependencies: []string{
			"github.com/barpilot/node-labeler-operator/pkg/apis/barpilot/v1alpha1.MergeSpec", "k8s.io/api/core/v1.NodeSelectorTerm"},
	}
}
